name: examen_practico
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  sqflite: ^2.2.8+1  # Dependencia para SQLite
  path: ^1.8.2       # Dependencia para manejar rutas de archivos
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
